In [2]:
import numpy as np

In [4]:
# Cria uma matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])
print(mt)
print(mt.dtype)
print(type(mt))

[12 34 26 18 10]
int32
<class 'numpy.ndarray'>


In [8]:
# Cria o array com um tipo especifico
# Cria o array como float de 64 bits:
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(mtfloat.dtype)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(mtint.dtype)
print(type(mtint))

[1. 2. 3.]
float64
<class 'numpy.ndarray'>
[1 2 3]
int32
<class 'numpy.ndarray'>


In [10]:
# mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [11]:
# podemos fazer o inverso:
mt5 =  np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [14]:
# mais de uma dimensão
# cria uma matriz bidimensional
mt7=  np.array([[7, 2, 23], [12, 27, 14], [6, 8, 9]])
print(mt7)

[[ 7  2 23]
 [12 27 14]
 [ 6  8  9]]
